config/routes.rb
Rails.application.routes.draw do
  post '/lists/:id/button', to: "follows#button", as: "follow_user"

  resources :users 
  resources :lists
  resources :searches
  
  resources :items do 
    resources :comments, only: [:create, :destroy]
  end

  get '/users/home' => 'users#home'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  root 'welcome#home' 

end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :creator, class_name: "User", optional: true
  has_many :follows, dependent: :destroy
  has_many :audiences, through: :follows
  has_many :items, dependent: :destroy
  has_many :comments, through: :items
  
  accepts_nested_attributes_for :items, reject_if:
  Proc.new {|attr| attr[:content].blank?}

  
  def items_of_status(status_input)
    items.select do |item|
      item.status == status_input
    end
  end

  def items_of_category(category)
    items.where(category: category)
  end

  def item_with_the_most_comments
    items.max_by { |item| item.comments.count }
  end

  def self.most_followed
    List.all.max_by{|list|list.follows.count}
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :find_list, only: [:show, :edit, :update]
	before_action :require_logged_in

	def index
			@lists = List.all
	end 
	
	def show
  end

	def new
	    @list = List.new
	end

	def create
	  @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
	end

	def edit
	end

	def update
    if @list.update(list_params)
	    redirect_to list_path(@list)
    else 
      render :edit
    end
	end

	def destroy
	  List.destroy(params[:id])
	  redirect_to lists_path
	end

	private

	def list_params
	  params.require(:list).permit(:title, :category, :creator_id, :search, items_attributes: [:content, :list_id, :status, :category])
	end

  def find_list
    @list = List.find(params[:id])
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_list_form.html.erb
<%= render partial: "/shared/error_message", locals: {variable: @list} %>

<%= form_for(@list) do |f| %>

   <%= f.label :title %>
   <%= f.text_field :title %><br>

   <%= f.hidden_field :creator_id, value: session[:user_id] %><br><br>

   <%= f.label :items, "Add an item to your list!" %><br><br>
   <%= f.fields_for :items, @list.items.build do |item_fields| %>
      <%= item_fields.label :content %>
      <%= item_fields.text_field :content %><br><br>
      <%= item_fields.label :status %>
      <%= item_fields.select :status, ["Not started yet", "In progress", "Finished"]%><br><br>
      <%= item_fields.label :category %>
      <%= item_fields.select :category, ["Food/Drink", "Travel/Destination", "Entertainment", "Nature/Wildlife", "Relationship", "Creativity", "Fashion/Beauty", "Other"] %>

      <%= item_fields.hidden_field :list_id, value: @list.id %>
   <% end %><br><br>

   <%= f.submit "Create a List" %>
<% end %>

app/views/lists/edit.html.erb
<body class="list_show_two_column">

  <div class="edit_forms">
      <div class="edit_your_object">Edit your list</div><br>
      <%= render "list_form" %>
  </div>

</body>

app/views/lists/index.html.erb
<div class="lists_search_form">
<%= form_for Search.new, url: searches_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :keywords %>
    <%= f.text_field :keywords %>

    <%= f.label :age_group, "Age Range" %>
    <%= f.text_field :min_age, size: 10 %> -
    <%= f.text_field :max_age, size: 10 %>

    <%= f.label :gender, "Gender" %>
    <%= f.select :gender, ["", "Male", "Female"]%>

    <%= f.submit "Search" %>
  </div>
<% end %>
</div> 


<div class="row lists_path_row">
  <% @lists.each do |list|%>
  <div class="col-sm-3">
    <div class="card">
      <%= image_tag("img#{rand(1..20)}.jpg", class:"card-img-top",id: "list_image") %>
      <div class="card-body">
        <h5 class="card-title"><%= list.title %></h5>
        <h6 class="card-subtitle mb-2 text-muted">by <%= list.creator.name %></h6>
        <a href="<%= list_path(list) %>" class="btn btn-outline-secondary">See this list</a>
      </div> 
    </div>
  </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="new_list_background"></div>

  <div class="new_list_form_wrapper">
  <%= render "list_form" %>
  </div>

app/views/lists/show.erb
<body class="list_show_two_column"> 
<div class="container list_show"> 
    <div class="row">
      <div class="col-sm-8 list_info">
          <div class="list_title"><%= @list.title%></div>
          <div class="list_creator">by <%= link_to @list.creator.name, user_path(@list.creator) %></div><br>
          <div class="follow_count">
              <%= pluralize(@list.follows.count, 'Follower')%></div>
          
          <div class="follow_button"><%= render "follows/button" %></div>

      <div class="each_list">
        <div class="notstartedyet_items">
            <ul>
                <% @list.items_of_status("Not started yet").each do |item| %>
                <li class="next_to_icon">
                    <div class="progress" >
                        <div class="progress-bar bg-success" role="progressbar" style="width: 0%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  <div class="d-flex">
                      <%= link_to item.content, item_path(item) %>
                      <% if current_user == @list.creator %>  
                      <div class="dropdown mr-1">
                        <button type="button" class="btn btn-outline-secondary dropdown-toggle" id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="10,20", style= "padding: 0px; font-size: 12px;">
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
                          <%= link_to "Edit", edit_item_path(item), class: "dropdown-item" %>
                          <%= link_to "Delete", item_path(item), method: :delete, class: "dropdown-item" %>
                        </div>
                      </div>
                      <% end %>
                  </div>
                    
                </li><br>
              <% end %>
             </ul>
        </div>
        <div class="inprogress_items">
            <ul>
                <% @list.items_of_status("In progress").each do |item| %>
                <li class="next_to_icon">
                    <div class="progress" >
                        <div class="progress-bar bg-success" role="progressbar" style="width: 50%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <div class="d-flex">
                        <%= link_to item.content, item_path(item) %>
                        <% if current_user == @list.creator %> 
                        <div class="dropdown mr-1">
                          <button type="button" class="btn btn-outline-secondary dropdown-toggle" id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="10,20", style= "padding: 0px; font-size: 12px;">
                          </button>
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
                            <%= link_to "Edit", edit_item_path(item), class: "dropdown-item" %>
                            <%= link_to "Delete", item_path(item), method: :delete, class: "dropdown-item" %>
                          </div>
                        </div>
                        <% end %>
                    </div>
                  </li><br>
              <% end %>
             </ul>
        </div>
        <div class="finished_items">
              <ul>
              <% @list.items_of_status("Finished").each do |item| %>
                <li class="next_to_icon">
                    <div class="progress" >
                        <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <div class="d-flex">
                        <%= link_to item.content, item_path(item) %>  
                        <% if current_user == @list.creator %>
                        <div class="dropdown mr-1">
                          <button type="button" class="btn btn-outline-secondary dropdown-toggle" id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="10,20", style= "padding: 0px; font-size: 12px;">
                          </button>
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
                            <%= link_to "Edit", edit_item_path(item), class: "dropdown-item" %>
                            <%= link_to "Delete", item_path(item), method: :delete, class: "dropdown-item" %>
                          </div>
                        </div>
                        <% end %>
                    </div>
                  </li><br>
              <% end %>
          </ul>
        </div>
      </div>
          <% if current_user == @list.creator %>
          <div class="edit_delete_buttons">
              <%= link_to "Edit this list", edit_list_path(@list), class: "btn btn-outline-dark", style: "color: white;" %>
            <%= link_to "Delete this list", list_path(@list), method: :delete, class: "btn btn-outline-dark"%>
          </div>
          <% end %>
      </div>
      <% if current_user == @list.creator %>
      <div class="col-sm-4">
        <div class="item_form_wrapper">
          <%= form_for @list.items.build do |f| %>
            <%= f.label :content, "Add a new Item to your list!" %>
            <%= f.text_field :content %><br><br>

            <%= f.label :status %>
            <%= f.select :status, ["Not started yet", "In progress", "Finished"]%><br><br>

            <%= f.label :category %>
            <%= f.select :category, ["Food/Drink", "Travel/Destination", "Entertainment", "Nature/Wildlife", "Relationship", "Creativity", "Fashion/Beauty", "Other"] %><br><br>

            <%= f.hidden_field :list_id, value: @list.id %>

            <%= f.submit %>
            <% end %>
          </div>
        </div>
        <% end %>
    </div>
</div>
</body>

app/views/lists/show.html.erb
<!-- <div class="container background"></div> -->

<div class="container list_show">
    <div class="row">
      <div class="col-sm-8 list_info">
          <div class="list_title"><%= @list.title%></div>
          <div class="list_creator">by <%= @list.creator.name%></div><br>
          <div class="follow_count">
          has <%= @list.follows.count %> follows</div>
          <div class="follow_button"><%= render "follows/button" %></div>
          <ul>
              <% @list.items.each do |item| %>
                <li><%= link_to item.content, item_path(item) %></li>
              <% end %>
          </ul>
          <% if current_user == @list.creator %>
          <div class="delete_list_button">
          <%= link_to "Delete this list", list_path(@list), method: :delete, class: "btn btn-secondary" %>
          </div>
          <% end %>
      </div>
      <% if current_user == @list.creator %>
      <div class="col-sm-4">
        <div class="item_form_wrapper">
          <%= form_for @list.items.build do |f| %>
            <%= f.label :content, "Add a new Item to your list!" %>
            <%= f.text_field :content %><br><br>

            <%= f.label :status %>
            <%= f.select :status, ["Not started yet", "In progress", "Finished"]%><br><br>

            <%= f.label :category %>
            <%= f.select :category, ["Food/Drink", "Travel/Destination", "Entertainment", "Nature/Wildlife", "Relationship", "Creativity", "Fashion/Beauty", "Other"] %><br><br>

            <%= f.hidden_field :list_id, value: @list.id %>

            <%= f.submit %>
            <% end %>
          </div>
        </div>
        <% end %>
    </div>
</div>

app/views/lists/ssssshow.html.erb
<div class="list_show"></div>

<div class="col-8 left_column">
    <div class="list_title"><%= @list.title%></div>
    <div class="list_creator">by <%= link_to @list.creator.name, user_path(@list.creator) %></div><br>
    <div class="follow_count">
    has <%= @list.follows.count %> follows</div>
    <div class="follow_button"><%= render "follows/button" %></div>
    <div class="each_item">
    <ul>
        <% @list.items.each do |item| %>
          <li><%= link_to item.content, item_path(item) %></li><br>
        <% end %>
    </ul>
  </div>
  <% if current_user == @list.creator %>
  <div class="delete_list_button">
  <%= link_to "Delete this list", list_path(@list), method: :delete, class: "btn btn-secondary" %>
  </div>
  <% end %>
</div>

<% if current_user == @list.creator %>
<div class="col-4 item_form_wrapper">
<div class="item_form">
    <%= form_for @list.items.build do |f| %>
      <%= f.label :content, "Add a new Item to your list!" %>
      <%= f.text_field :content %><br><br>

      <%= f.label :status %>
      <%= f.select :status, ["Not started yet", "In progress", "Finished"]%><br><br>

      <%= f.label :category %>
      <%= f.select :category, ["Food/Drink", "Travel/Destination", "Entertainment", "Nature/Wildlife", "Relationship", "Creativity", "Fashion/Beauty", "Other"] %><br><br>

      <%= f.hidden_field :list_id, value: @list.id %>

      <%= f.submit %>
    <% end %>
</div>
</div>
<% end %>



 