config/routes.rb
Rails.application.routes.draw do
  post '/lists/:id/button', to: "follows#button", as: "follow_user"

  resources :users 
  resources :lists
  resources :searches
  
  resources :items do 
    resources :comments, only: [:create, :destroy]
  end

  get '/users/home' => 'users#home'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  root 'welcome#home' 

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :audience, class_name: "User"
  belongs_to :item

  validates :content, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :require_logged_in

    def create
        @item = Item.find(params[:item_id])
        @comment = @item.comments.create(comment_params)
        
        redirect_to item_path(@item)
    end 
 
    def destroy
        @item = Item.find(params[:item_id])
        @comment = @item.comments.find(params[:id])
        @comment.destroy

        redirect_to item_path(@item)
    end    

    private
    def comment_params
        params.require(:comment).permit(:content, :audience_id, :item_id)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<a href="<%= list_path(@item.list) %>" class="btn btn-outline-info btn-lg to_the_list">Go back to the list</a>
<h4 class="item_title"><%= @item.content%></h4>
<h6><%= pluralize(@item.comments.count, "comment")%> for this item</h6>
<div class="card-columns">
    <% @item.comments.each do |comment| %>
        <div class="card each_comment <%=["font1","font2","font3","font4","font5","font6","font7"].sample %>" style="width: 18rem;">
                <div class="card-body comment_background_each">
                    <h5 class="card-title"><%= comment.content %></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><%= distance_of_time_in_words(Time.now, comment.created_at)%> ago</h6>
                    <a href="#" class="card-link"><%= link_to comment.audience.fullname, user_path(comment.audience) %></a>
                    <a href="#" class="card-link"><% if current_user == comment.audience %>
                        (<%= link_to "delete comment", item_comment_path(@item, comment), method: :delete %>)
                        <% end %></a>
                </div>
        </div>
    <%end%>
<div id="comment_form" class="card"><%= render "comments/form" %></div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@item, @item.comments.build]) do |f| %>
<%= f.text_area :content, placeholder: "Comment", class: "textarea" %>
<%= f.hidden_field :audience_id, value: current_user.id %>
<div class= "spacer_between_submit"></div>
<%= f.button :submit,:class => 'btn btn-warning' %>
<% end %>

app/views/comments/new.html.erb
<%= render "form" %>

app/views/comments/show.html.erb
<%= render "comment" %>