config/routes.rb
Rails.application.routes.draw do
  post '/lists/:id/button', to: "follows#button", as: "follow_user"

  resources :users 
  resources :lists
  resources :searches
  
  resources :items do 
    resources :comments, only: [:create, :destroy]
  end

  get '/users/home' => 'users#home'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  root 'welcome#home' 

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :lists, foreign_key: "creator_id"
  has_many :items, through: :lists, foreign_key: "creator_id"
  has_many :follows, through: :lists, foreign_key: "creator_id"
  has_many :loves, class_name: "Follow", foreign_key: "audience_id"
  has_many :comments, foreign_key: "audience_id"
 
  ## As a audience
  has_many :love_lists, :through => :loves, :source => :list
  has_many :creators, :through => :love_lists, :foreign_key => :creator_id

  ## As a creator
  has_many :audiences, :through => :follows, :class_name => "User"

  accepts_nested_attributes_for :lists, reject_if:
  Proc.new {|attr| attr[:title].blank?}

  validates :name, presence: true, uniqueness: {case_sensitive: false}

  

  def most_followed_list_of_me
    my_list = List.all.select { |list| list.creator == self }
    my_list.all.max_by { |list| list.follows.count }
  end

  #find lists of the creators whoes age is +-3 years from me
  def lists_of_my_age_group
    List.all.select { |list| list.creator.age >= self.age - 3 && list.creator.age <= self.age + 3 }
  end

  def lists_of_my_gender
    List.all.select { |list| list.creator.gender == self.gender }
  end

  def total_follows
    follows = []
    self.lists.each do |list| 
      list.follows.each do |follow|
        follows << follow
      end
    end
    follows.count
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def home
	end

	def index
	  @users = User.all
	end 
	
	def show
		@user = User.find(params[:id])
  	end

	def new

	end

	def create
		@user = User.new(user_params)
    if @user.save
			return redirect_to controller: 'users', action: 'new' unless @user.save
			session[:user_id] = @user.id
			redirect_to controller: 'welcome', action: 'home'
    else
      render :new
		end
	end

	def edit
		# byebug
	end

	def update
    if @user.update(user_params)
	    redirect_to user_path(@user)
    else 
      render :edit
    end
	end

	def destroy
		current_user.destroy
	  redirect_to users_path
	end

	private

	def user_params
		params.require(:user).permit(:name, :password, :password_confirmation, :fullname, :age, :gender, lists_attributes: [:title, :creator_id])
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<%= render partial: "shared/error_message", locals: {variable: @user} %>

<%= form_for current_user do |f| %>
  <%= f.label :name, "Username" %>
  <%= f.text_field :name %><br><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br><br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br><br>

  <%= f.label :fullname %>
  <%= f.text_field :fullname %><br><br>

  <%= f.label :age %>
  <%= f.select :age, (1..110) %><br><br>

  <%= f.label :gender %>
  <%= f.select :gender, ["Male", "Female", ""] %><br><br><br>

  <%= f.label :lists, "Add your first Bucketlist! (Optional)"%><br><br>
  <%= f.fields_for :lists, current_user.lists.build do |field| %>
     <%= field.label :title %>
     <%= field.text_field :title %>
     <%= field.hidden_field :creator_id, value: current_user.id %>
  <% end %>
  
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<div class="background"></div>
<div class="newaccount">
  <h4>Edit your profile</h4>
  <%= render "user_form" %>
</div>

app/views/users/index.html.erb
<h1>All the users:</h1>

<ul>
   <% @users.each do |user| %>
      <li><%= user.name %></li>
   <% end %>
</ul>
<%= link_to "Create New User", new_user_path %>

app/views/users/new.html.erb
<div class="background"></div>

<div class="newaccount">
  <h4>Create a new account</h4>
  <%= render "user_form" %>
</div>

app/views/users/show.html.erb
<div class="outside_container_show">
  <div class="profile_box_start"> </div>
    <div class="container container_main">
      <div class="row top_row"> 
        <div class="col profile_div">
          <h1 class="profile_title">LYSTER BIO</h1>
          <img src= "/assets/profile_pic" /> 
          <div class= "profile_info">
            <h3><%=@user.name%></h3> 
            <h4>
              <%=@user.fullname%> is a <%=@user.age%> year old <%=@user.gender.downcase%>.
            </h4>
            <% if @user == current_user %>
            <div><%= link_to "Edit my profile", edit_user_path(@user), class: "btn btn-outline-secondary" %>
            <%= link_to "Make a new bucketlist", new_list_path, class: "btn btn-outline-secondary" %></div><br>
            <% end %>
            <div id="mini_stats" class="container">
                <div class="row three_rows">
                  <div class="col">
                    <h6><%= @user.lists.count %></h6>
                    <p><%= @user.lists.count == 1 ? "List" : "Lists" %></p>
                  </div>
                  <div class="col">
                    <h6><%= @user.total_follows %></h6>
                    <p><%= @user.total_follows == 1 ? "Follow" : "Follows" %></p>
                  </div>
                  <div class="col">
                    <h6><%= @user.love_lists.count %></h6>
                    <p>Following</p>
                  </div>
                  <div class="col">
                    <h6><%= @user.comments.count %></h6>
                    <p><%= @user.comments.count == 1 ? "Comment" : "Comments" %></p>
                  </div>
                </div>
              </div>
          </div>
        </div>
     
      <div class="container">
        <div class="row">
          <div class="col buckets_list">
            <h5 class="become_black">Bucketlists you have created:</h5>
            <ul>
              <% @user.lists.each do |list| %>
                <li><%=link_to list.title, list_path(list)%></li>
              <% end %>
            </ul>
          </div>
          <div class="col followed_list">
            <h5 class="become_black">Bucketlists you have followed:</h5>
            <ul>
              <% @user.love_lists.each do |list| %>
                <li><%= link_to list.title, list_path(list) %></li>
              <% end %>
            </ul>
          </div>
          <div class="col comments_list become_black">
            <h5>Comments you have made:</h5>
            <% @user.comments.reverse.each do |comment| %>
              <li>  <%= link_to comment.content, item_path(comment.item) %> - <%= distance_of_time_in_words(Time.now, comment.created_at)%></li>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="profile_box_end">
  </div>
</div>