config/routes.rb
Rails.application.routes.draw do
  post '/lists/:id/button', to: "follows#button", as: "follow_user"

  resources :users 
  resources :lists
  resources :searches
  
  resources :items do 
    resources :comments, only: [:create, :destroy]
  end

  get '/users/home' => 'users#home'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  root 'welcome#home' 

end

app/models/search.rb
class Search < ApplicationRecord

  def find_lists
    lists = List.all
    lists = lists.where("title like ?", "%#{keywords}%") if keywords.present?
    lists = lists.select { |list| list.creator.age >= min_age } if min_age.present?
    lists = lists.select { |list| list.creator.age <= max_age } if max_age.present?
    lists = lists.select { |list| list.creator.gender == gender } if gender.present?
    lists
  end

end
 

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
  end

  def create
    @search = Search.create(search_params)
    redirect_to search_path(@search)
  end
  
  def show
    @search = Search.find(params[:id])
  end

  private

  def search_params
    params[:search].permit(:keywords, :gender, :min_age, :max_age)
  end


end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.erb
<h1>Advanced Search</h1>
 
<%= form_for @search do |f| %>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :age_group, "Age Range" %><br />
    <%= f.text_field :min_age, size: 10 %> -
    <%= f.text_field :max_age, size: 10 %>
  </div>
  <div class="field">
      <%= f.label :gender, "Gender" %><br />
      <%= f.select :gender, ["", "Male", "Female"]%>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>

app/views/searches/show.html.erb
<div class="lists_search_form">
    <%= form_for @search, url: searches_path, method: :post do |f| %>
      <div class="field">
        <%= f.label :keywords %>
        <%= f.text_field :keywords %>
    
        <%= f.label :age_group, "Age Range" %>
        <%= f.text_field :min_age, size: 10 %> - 
        <%= f.text_field :max_age, size: 10 %>
    
        <%= f.label :gender, "Gender" %>
        <%= f.select :gender, ["", "Male", "Female"]%>
    
        <%= f.submit "Search" %>
      </div>
    <% end %>
</div> 

<div class="row lists_path_row">
    <% @search.find_lists.each do |list|%>
    <div class="col-sm-3">
      <div class="card">
        <%= image_tag("img#{rand(1..20)}.jpg", class:"card-img-top",id: "list_image") %>
        <div class="card-body">
          <h5 class="card-title"><%= list.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted">by <%= list.creator.name %></h6>
          <a href="<%= list_path(list) %>" class="btn btn-outline-secondary">See this list</a>
        </div> 
      </div>
    </div>
    <% end %>
  </div>

  <div class="filtered_lists">
      <a href="<%= lists_path %>" class="btn btn-outline-info btn-lg to_all_lists">Go back to All Lists</a>
  </div>